version: '3.8'
services:
  mongodb-entity:
    container_name: ${MODE}-mongodb-entity-compose
    image: mongo:7.0.2
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ${MONGO_VOLUME}:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}

  redis-entity:
    container_name: ${MODE}-redis-entity-compose
    image: redis/redis-stack:latest
    ports:
      - "${REDIS_PORT}:6379"
      - "${REDIS_INSIGHT_PORT}:8001"
    volumes:
      - ${REDIS_VOLUME}:/data
    environment:
      - REDIS_ARGS=${REDIS_ARGS}

  redis-to-mongo-sync-script:
    build: .
    depends_on:
      - mongodb-entity
      - redis-entity
    restart: on-failure
    environment:
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - MONGO_DB_USER=${MONGO_DB_USER}
      - MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}
      - MONGO_HOST=mongodb-entity
      - MONGO_PORT=27017
      - REDIS_HOST=redis-entity
      - REDIS_PORT=6379
      - SYNC_INTERVAL_SEC=${SYNC_INTERVAL_SEC}
      - MESSAGES_PER_STREAM=${MESSAGES_PER_STREAM}
      - MODE=${MODE}
