version: '3.8'
services:
  mongo:
    container_name: mongodb-entity
    image: mongo:7.0.2
    ports:
      - "27017:27017"
    volumes:
      - ${MONGO_VOLUME}:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

  redis:
    image: redis
    command: redis-server --appendonly yes --save ${REDIS_RDB_TIME} 1 --loglevel warning
    ports:
      - "6379:6379"
    volumes:
      - ${REDIS_VOLUME}:/data

  script:
    build: .
    depends_on:
      - mongo
      - redis
