version: '3.8'
services:
  mongodb-entity:
    container_name: mongodb-entity
    image: mongo:7.0.2
    ports:
      - "27017:27017"
    volumes:
      - ${MONGO_VOLUME}:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}

  redis-entity:
    container_name: redis-entity
    image: redis/redis-stack:latest
    command: redis-server --appendonly yes --save ${REDIS_RDB_TIME} 1 --loglevel warning
    ports:
      - "6379:6379"
    volumes:
      - ${REDIS_VOLUME}:/data

  redis-to-mongo-sync-script:
    build: .
    depends_on:
      - mongo
      - redis
    restart: on-failure
    environment:
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - MONGO_HOST=${MONGO_HOST}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - SYNC_INTERVAL_SEC=${SYNC_INTERVAL_SEC}
      - MESSAGES_PER_STREAM=${MESSAGES_PER_STREAM}
